baseURL = "https://my-blog-omega-azure.vercel.app/"
languageCode = "zh-cn"
hasCJKLanguage = true
title = "落弦尘的博客"
theme = "hugo-theme-reimu"

[params]
  author = "落弦尘"
  authorAvatar = "327DA22503217DD76960462F8D6B9F16.jpg"
  description = "如果能久别重逢，我希望你别来无恙。"
  vercel_analytics = true

  socialIcons = [
    { name = "github", url = "https://github.com/DreamCatcher-6298586" }
  ]

  [params.comments]
    enabled = true
    type = "utterances"
    repo = "DreamCatcher-6298586/my-blog"

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 2
